### ISSUE TITLE
mac os 10.14 可以休眠和唤醒吗？ sleep/awake works on mac os 10.14?

### ISSUE THREAD

**Issue by dorado-lmz** [lonecloud/Hackintosh#1]
系统一旦进入休眠状态，主机应该处于休眠了（电源灯还亮着），通过敲击键盘，主机风扇开始转了（我想应该是唤醒了吧，未确认），但是显示器依然是休眠。
每次遇到这种情况，我只能重启系统。 
Once the system enters the sleep state, computer should be in hibernation (the power light is still on). By tapping the keyboard, computer fan starts to turn (I think it should be awake, unconfirmed), but the display is still sleep.Every time I encounter this situation, I can only restart the system.

---
主板：微星 z270i
mainboard: msi z270i
cpu: i5-7500 hd630
memory: Micron DDR4 2400

**Comment by lonecloud** [comment]
休眠唤醒暂时无解，我现在强制打开这个，防止电脑睡眠可以暂时解决该问题
![image](https://user-images.githubusercontent.com/17854123/50151193-25754500-02fb-11e9-9d4d-666027477de8.png)
