### ISSUE TITLE
我的主板和CPU都是和你的一样的，也没有独显，请问我可以直接用你的EFI文件吗？谢谢！

### ISSUE THREAD

**Issue by yomizzz** [lonecloud/Hackintosh#2]
我的配置如下：
CPU：i5-7500
主板：技嘉B250M-DS3H
内存：十铨 elite系列 DDR4 2400 8G
硬盘：东芝Q200EX 240G SSD

**Comment by lonecloud** [comment]
可以的，直接用就可以了，如果有问题的话，可以给我提问题哈

**Comment by yomizzz** [comment]
请问这个主板我要怎么把它的secure boot mode关掉？我刚试了一次就卡在苹果界面了，安装不下去了，谢谢解答。

**Comment by lonecloud** [comment]
> 请问这个主板我要怎么把它的secure boot mode关掉？我刚试了一次就卡在苹果界面了，安装不下去了，谢谢解答。
查看该链接：
https://www.icharm.me/%E6%8A%80%E5%98%89gigabyte-b350m-gaming-3-%E5%85%B3%E9%97%AD-secure-boot.html
